# Generated by Django 5.1.1 on 2024-12-12 17:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sensorreading_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(1986, 1, 1, 7, 23, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(datetime.datetime(2024, 12, 12, 17, 6, 43, tzinfo=datetime.timezone.utc))]),
        ),
    ]
