# Generated by Django 5.1.1 on 2024-12-12 18:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sensorreading_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(1986, 1, 1, 12, 0))]),
        ),
    ]
