# Generated by Django 5.1.4 on 2024-12-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sensor_installed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='scheduled_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='installed_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
